name: Semgrep-Java&JS
on: [push, pull_request]
jobs:
    semgrepJava:
        runs-on: ubuntu-latest
        name: semgrepJava
        steps:
            - uses: actions/checkout@v2
            - uses: returntocorp/semgrep-action@v1
              with:
                config: p/java
                output: ./semgrep-results.json
            - uses: peter-evans/create-issue-from-file@v2
              with:
                title: Semgrep-output
                content-filepath: ./semgrep-results.json
                labels: report, automated issue



    # semgrepJS:
    #     runs-on: ubuntu-latest
    #     name: semgrepJS
    #     steps:
    #         - uses: actions/checkout@master
    #         - uses: returntocorp/semgrep-action@v1
    #           with:
    #             config: p/javascript
