name: Semgrep-Java&JS
on: [push, pull_request]
jobs:
    semgrepJava:
        runs-on: ubuntu-latest
        name: semgrepJava
        steps:
            - uses: actions/checkout@master
            - uses: returntocorp/semgrep-action@v1
              with:
                config: p/java
    semgrepJS:
        runs-on: ubuntu-latest
        name: semgrepJS
        steps:
            - uses: actions/checkout@master
            - uses: returntocorp/semgrep-action@v1
              with:
                config: p/javascript                